# -*- coding: utf-8 -*-
"""SISTEMA DE LOGIN Y CONTRASEÑA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DRdVsbTIW8nJcIe9M0Z4JpfVV0x0eUdw
"""

usuario_valido = input("Ingrese su usuario (También podés usar mayusculas) ")
contraseña_valida = input("Ingrese su contraseña ")

while len(contraseña_valida) <= 4:
    print("Su contraseña es erronea. Debe contener mas de 4 caracteres")
    contraseña_valida = input("¿Cual sera tu contraseña? ") 
    if len(contraseña_valida) >4:
      break

#-------------------------------------------------------------------------------

print("¡Excelente, has creado tu cuenta!")
print("Es hora de loguearte")

usuario = input("Ingrese su usuario ")
contraseña = input("Ingrese su contraseña ")
intentos = 3

while intentos >= 0: #Si las credenciales son correctas
    if usuario == usuario_valido and contraseña == contraseña_valida:
     print("El usuario y la contraseña son validos")
     break

    elif usuario != usuario_valido and contraseña != contraseña_valida: #Si no coincide ninguno
     print("No coinciden las credenciales ingresadas")
     usuario = input("Ingrese un usuario ")
     contraseña = input("Ingrese una contraseña")

    elif usuario != usuario_valido: #Si no coincide el usuario
     print("Los usuarios no coinciden, intente de nuevo")
     usuario = input("Ingrese un usuario ")
     contraseña = input("Ingrese una contraseña ")

    elif contraseña != contraseña_valida: #Si no coincide la contraseña
     print("Las contraseñas no coinciden, intente de nuevo")
     usuario = input("Ingrese un usuario ")
     contraseña = input("Ingrese una contraseña ")

    

print("Bienvenido a la plataforma de la concha de tu hermana, es un gusto que te hayas registrado")

#-------------------------------------------------------------------------------

print("Ahora es turno de ingresar tus datos personales")

pais = input("¿De que pais sos?")
provincia = input("¿De que provincia eres?")
email = input("Te voy a llenar la casilla de spam asi que ingresa tu email")